VAR1 = Nuno Miguel Carvalho de Jesus#The variable ends here
VAR2 = Nuno Miguel Carvalho de Jesus #The variable ends here

all:
ifeq ($(VAR1), Nuno Miguel Carvalho de Jesus)
	@echo "VAR1 contains my name"
else
	@echo "VAR1 does not contain my name"
endif

ifeq ($(VAR2), Nuno Miguel Carvalho de Jesus)
	@echo "VAR2 contains my name"
else
	@echo "VAR2 does not contain my name"
endif
